### ISSUE TITLE
Persistent client crash on login: java.lang.ClassCastException: mods.immibis.lxp.CollectorTile cannot be cast to mcp.mobius.betterbarrels.common.blocks.TileEntityBarrel

### ISSUE THREAD

**Issue by satoshinm** [satoshinm/modpack#102]
```
[19:59:09] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:09] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:09] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:10] [Client thread/WARN] [OpenComputers]: Error in item tooltip.
java.lang.ArrayIndexOutOfBoundsException: 32767
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel JABBA
java.lang.ClassCastException: mods.immibis.lxp.CollectorTile cannot be cast to mcp.mobius.betterbarrels.common.blocks.TileEntityBarrel
    at mcp.mobius.betterbarrels.network.Message0x00FulleTileEntityNBT.channelRead0(Message0x00FulleTileEntityNBT.java:44) ~[Message0x00FulleTileEntityNBT.class:?]
    at mcp.mobius.betterbarrels.network.Message0x00FulleTileEntityNBT.channelRead0(Message0x00FulleTileEntityNBT.java:10) ~[Message0x00FulleTileEntityNBT.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[19:59:14] [Netty Client IO #3/INFO] [THAUMCRAFT]: Restoring client configs.
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
[19:59:14] [Netty Client IO #3/INFO] [EnderCore]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[19:59:14] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.EOFException
```

**Comment by satoshinm** [comment]
Not fixed by client-side change in config/forge.cfg 

    B:removeErroringEntities=true
    B:removeErroringTileEntities=true

edit to remove with MCEdit Unified http://podshot.github.io/MCEdit-Unified/ or NBT Explorer https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac

**Comment by satoshinm** [comment]
Conflict `immibis.lxp.collector` vs `TileEntityBarrel`. Searched for all tile entities, using https://github.com/mcedit/pymclevel with this script:

```python
#!/usr/bin/env python
import mclevel

filename = "/tmp/server/world"

level = mclevel.fromFile(filename)

print level

for i, cPos in enumerate(level.allChunks):
    try:
        chunk = level.getChunk(*cPos)
    except mclevelbase.ChunkMalformed:
        continue

    for tileEntity in chunk.TileEntities:
        id = tileEntity["id"].value
        if 'GT_TileEntity_Ores' == id: continue

        print id
        if 'immibis' in id:
            print tileEntity["x"].value, tileEntity["y"].value, tileEntity["z"].value

    if i % 100 == 0:
        print "Chunk {0}...".format(i)
```

There were immibis.lxp.enchanter, immibis.lxp.absorber, immibis.lxp.imprinter, immibis.lxp.combiner, and immibis.lxp.enchanter but no collector. Two TileEntityBarrel entities.

Unchecked cast in server/mods/Jabba-1.2.2_1.7.10.jar ./mcp/mobius/betterbarrels/network/Message0x00FulleTileEntityNBT.class

```java
   protected void channelRead0(ChannelHandlerContext ctx, Message0x00FulleTileEntityNBT msg) throws Exception {
      TileEntityBarrel barrel = (TileEntityBarrel)Minecraft.func_71410_x().field_71441_e.func_147438_o(msg.x, msg.y, msg.z);
      if(barrel != null) {
         barrel.func_145839_a(msg.fullTETag);
      }
   }
```

**Comment by satoshinm** [comment]
If repairing/working around this error, there is another one behind it:

[15:04:25] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel CoFH
io.netty.handler.codec.DecoderException: java.lang.ClassCastException: cofh.thermaldynamics.duct.item.TileItemDuct cannot be cast to cofh.thermaldynamics.duct.fluid.TileFluidDuct
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ClassCastException: cofh.thermaldynamics.duct.item.TileItemDuct cannot be cast to cofh.thermaldynamics.duct.fluid.TileFluidDuct
	at cofh.thermaldynamics.duct.attachments.servo.ServoFluid.<init>(ServoFluid.java:29) ~[ServoFluid.class:?]
	at cofh.thermaldynamics.block.AttachmentRegistry.createAttachment(AttachmentRegistry.java:28) ~[AttachmentRegistry.class:?]
	at cofh.thermaldynamics.block.TileTDBase.handleTilePacket([LP|ASM] TileTDBase.java:968) ~[TileTDBase.class:?]
	at cofh.thermaldynamics.duct.item.TileItemDuct.handleTilePacket(TileItemDuct.java:629) ~[TileItemDuct.class:?]
	at cofh.core.network.PacketTile.handlePacket(PacketTile.java:31) ~[PacketTile.class:?]
	at cofh.core.network.PacketCoFHBase.handleClientSide(PacketCoFHBase.java:404) ~[PacketCoFHBase.class:?]
	at cofh.core.network.PacketHandler.decode(PacketHandler.java:98) ~[PacketHandler.class:?]
	at cofh.core.network.PacketHandler.decode(PacketHandler.java:40) ~[PacketHandler.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
	... 26 more

This may indicate severe corruption?

**Comment by satoshinm** [comment]
Restored from backup :-/
