### ISSUE TITLE
Add Tinker's Construct and related mods

### ISSUE THREAD

**Issue by satoshinm** [satoshinm/modpack#36]
Another early-game alternative progression than GregTech, but be mindful of compatibility

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2218638-tinkers-construct-2 TConstruct-1.7.10-1.8.8.jar Tinker's Construct https://ftbwiki.org/Tinkers%27_Construct

Tinker's Mechworks? https://ftbwiki.org/Tinkers%27_Mechworks

~~Tinker's Steelworks https://ftbwiki.org/Tinkers%27_Steelworks https://mods.curse.com/mc-mods/minecraft/233076-tinkers-steelworks-fork#t1:description~~ - requires cookiecore, only adds high oven, skipping it

ExtraTiC? https://ftbwiki.org/ExtraTiC

TiC Tooltips? https://ftbwiki.org/TiC_Tooltips

Natura? https://ftbwiki.org/Natura

BiblioWoods-Natura https://ftbwiki.org/BiblioWoods_Natura

**Comment by satoshinm** [comment]
OK, the mod is denying this combination:

```
[23:38:58] [Client thread/INFO] [TConstruct]: Natura, what are we going to do tomorrow night?
[23:38:58] [Client thread/INFO] [Natura]: TConstruct, we're going to take over the world!
[23:38:58] [Client thread/ERROR] [TConstruct]: Tinkers' Construct and GregTech are incompatible for the following reasons:
[23:38:58] [Client thread/ERROR] [TConstruct]: - GregTech is a meta-mod that changes how a lot of mods interact with the base game and with each other.
- The mod restructures the registration of various ores within the Ore Dictionary. This may alter or break the original design intention of various other mods.
- This mod alters various fundamental recipes from vanilla Minecraft.
```

then

```
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	CoFHCore: -[1.7.10]3.1.4-329
	MineFactoryReloaded: -[1.7.10]2.8.2B1-201
	Mantle Environment: Environment healthy.
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	TConstruct Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: gregtech
	RedstoneArsenal: -[1.7.10]1.1.2-92
	ThermalDynamics: -[1.7.10]1.2.1-172
[23:39:03] [Client thread/INFO] [STDOUT]: [net.minecra
```

**Comment by satoshinm** [comment]
Maybe Tinkers' Gregworks? https://github.com/Vexatos/TinkersGregworks
Some background: https://www.reddit.com/r/feedthebeast/comments/1t8jlr/mdiyo_you_wont_be_able_to_use_tconstruct_and/ and https://forum.industrial-craft.net/thread/9955-about-the-tinkers-construct-problem-you-might-got-linked-from-my-dropbox-based-i/

**Comment by satoshinm** [comment]
The check is in https://github.com/SlimeKnights/TinkersConstruct/blob/1.7.10/src/main/java/tconstruct/util/EnvironmentChecks.java#L29:

```java
    /**
     * Checks for conflicting stuff in environment; adds callable to any crash
     * logs if so. Note: This code adds additional data to crashlogs. It does
     * not trigger any crashes.
     */
    private static List<String> incompatibilities = new ArrayList<String>();
    private static EnvironmentChecks instance = new EnvironmentChecks();

    public static void verifyEnvironmentSanity ()
    {
        List<String> modIds = new ArrayList<String>();

        if (Loader.isModLoaded("gregtech"))
        {
            TConstruct.logger.error("Tinkers' Construct and GregTech are incompatible for the following reasons:");
            TConstruct.logger.error(modCompatDetails("GregTech", true));
            modIds.add("gregtech");
            incompatibilities.add("GregTech");
        }

        // Bukkit/Magic Launcher/Optifine are caught by Mantle, so we no longer
        // check for those.
```

it doesn't crash on the server, only client, so it was a real crash to debug. And actually a different error - the problem was moving client-side mods out of the way for server, but after moving them back, can launch, no more crash:

```
[23:39:03] [Client thread/INFO] [STDOUT/]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 6/22/17 11:39 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: ic2backpackhud.IC2BackpackHUD
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
    at org.multimc.EntryPoint.listen(EntryPoint.java:162)
    at org.multimc.EntryPoint.main(EntryPoint.java:53)
Caused by: java.lang.ClassNotFoundException: ic2backpackhud.IC2BackpackHUD
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:58)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
    ... 18 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 45 more
```
