### ISSUE TITLE
Steve's Carts: [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.FileNotFoundException: https://dl.dropboxusercontent.com/u/46486053/RemoteInfo.txt

### ISSUE THREAD

**Issue by satoshinm** [satoshinm/modpack#4]
Something is trying to access a non-existent file on DropBox:

```
[20:20:59] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: planetguyLib in /Applications/MultiMC.app/Contents/MacOS/instances/1.7.10 Beyond Reality/minecraft/mods/1.7.10/PlanetguyLib-1.9.2.jar
[20:20:59] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: planetguyLib in /Applications/MultiMC.app/Contents/MacOS/instances/1.7.10 Beyond Reality/minecraft/mods/1.7.10/PlanetguyLib-1.9.2.jar
[20:20:59] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: planetguyLib in /Applications/MultiMC.app/Contents/MacOS/instances/1.7.10 Beyond Reality/minecraft/mods/1.7.10/PlanetguyLib-1.9.2.jar
[20:20:59] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.FileNotFoundException: https://dl.dropboxusercontent.com/u/46486053/RemoteInfo.txt
[20:20:59] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
[20:20:59] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
[20:20:59] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1466)
[20:20:59] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1464)
[20:20:59] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[20:20:59] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[20:20:59] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1463)
[20:20:59] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[20:20:59] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at vswe.stevescarts.Fancy.FancyPancyLoader.run(FancyPancyLoader.java:51)
[20:20:59] [Thread-7/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by satoshinm** [comment]
Searching for other links containing https://dl.dropboxusercontent.com/u/46486053 - https://www.reddit.com/r/feedthebeast/comments/2ya2we/where_to_download_steves_factory_manager/ this appears to be the dropbox account of Vswe, the author of Steve's Carts.
