### ISSUE TITLE
GraviSuite: [FML]: Unable to determine registrant mod for com.estebes.gravisuitereloaded.item.tool.ItemToolTheChopper@4f511f42. This is a critical error and should be impossible

### ISSUE THREAD

**Issue by satoshinm** [satoshinm/modpack#5]
GraviSuite Reloaded has an "impossible" error, being unable to determine the "registrant mod" - what does this mean and why?

```
[20:20:59] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[20:20:59] [Client thread/ERROR] [FML]: Unable to determine registrant mod for com.estebes.gravisuitereloaded.item.tool.ItemToolTheChopper@4f511f42. This is a critical error and should be impossible
java.lang.Throwable
	at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:55) [EventBus.class:?]
	at com.estebes.gravisuitereloaded.item.tool.ItemToolTheChopper.<init>(ItemToolTheChopper.java:35) [ItemToolTheChopper.class:?]
	at com.estebes.gravisuitereloaded.init.ItemInit.<clinit>(ItemInit.java:23) [ItemInit.class:?]
	at java.lang.Class.forName0(Native Method) [?:1.8.0_131]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_131]
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:70) [ObjectHolderRegistry.class:?]
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:39) [ObjectHolderRegistry.class:?]
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:554) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
[20:20:59] [Client thread/INFO] [FML]: Found 120 ObjectHolder annotations
```

**Comment by satoshinm** [comment]
Searching for this specific error finds only other reports of it no solution, but the general error "Unable to determine registrant mod" points to https://github.com/MinecraftForge/FML/issues/563 which says it is hyperbole:

> It is rather critical for some older stuff we were doing with the event system.
> That we were forced to take out because modders were abusing it to make it look like other mods were the cause of problems.
> Without it we do not know who is responsible for what code being run.
> the rest of the internal message is 'but modders were twats and forced us to make it possible'
> But this is what we get for trying to enforce some form of order or maintainability on the minecraft community.
