### ISSUE TITLE
Aroma1997s Dimensions: net.minecraft.util.ReportedException: Exception getting block type in world

### ISSUE THREAD

**Issue by satoshinm** [satoshinm/modpack#55]
After traveling afar in the mining world, the server crashed:

```
[15:58:26 WARN]: Failed to handle packet for /127.0.0.1:58620
net.minecraft.util.ReportedException: Exception getting block type in world
	at net.minecraft.world.World.func_147439_a(World.java:711) ~[ahb.class:?]
	at net.minecraft.world.World.func_98179_a(World.java:3740) ~[ahb.class:?]
	at net.minecraft.world.World.updateLightByType(World.java:3871) ~[ahb.class:?]
	at net.minecraft.world.World.func_147463_c(World.java:4947) ~[ahb.class:?]
	at net.minecraft.world.World.func_147451_t(World.java:3728) ~[ahb.class:?]
	at net.minecraft.world.World.func_147465_d(World.java:875) ~[ahb.class:?]
	at net.minecraft.world.gen.feature.WorldGenLiquids.func_76484_a(SourceFile:37) ~[asm.class:?]
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:337) ~[aia.class:?]
	at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:130) ~[aia.class:?]
	at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339) ~[ahu.class:?]
	at aroma1997.world.dimension.BiomeGenMining.func_76728_a(BiomeGenMining.java:43) ~[BiomeGenMining.class:?]
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:426) ~[aqz.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:442) ~[ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1196) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:311) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:217) ~[ms.class:?]
	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:408) ~[mr.class:?]
	at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:121) ~[mq.class:?]
	at net.minecraft.server.management.PlayerManager.func_72691_b(PlayerManager.java:228) ~[mq.class:?]
	at net.minecraft.server.management.PlayerManager.func_72685_d(PlayerManager.java:305) ~[mq.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72358_d(ServerConfigurationManager.java:421) ~[oi.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:593) ~[nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) ~[jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(C03PacketPlayer.java:234) ~[jf.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.World.func_72827_u()Ljava/lang/String;
	at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:109) ~[aia.class:?]
	at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339) ~[ahu.class:?]
	at aroma1997.world.dimension.BiomeGenMining.func_76728_a(BiomeGenMining.java:43) ~[BiomeGenMining.class:?]
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:426) ~[aqz.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:442) ~[ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1196) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:311) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:217) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:185) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:323) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:799) ~[ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:702) ~[ahb.class:?]
	... 30 more
```

**Comment by satoshinm** [comment]
Found this: https://github.com/CyberdyneCC/Thermos/issues/441 - was supposed to be fixed in https://github.com/CyberdyneCC/Thermos/issues/490 build 58 but 57 is considered stable, there are other changes which cause other issues?
